database:
  driver: "mysql"
  dbname: "rxSecure"
  username: "root"
  password: "password"
#  host: "docker.for.mac.localhost"
  host: "127.0.0.1"
  port: "3306"
  logmode: true

server:
  port: "8081"

databaseSelection:
  keys: "mysql"
  payload: "mysql"